import { contextBridge, ipcRenderer } from 'electron';
const invoke = <T>(channel: string, ...args: unknown[]): Promise<T> => ipcRenderer.invoke(channel, ...args) as Promise<T>;
contextBridge.exposeInMainWorld('filebeam', {
  server: { start: () => invoke('server:start'), stop: () => invoke('server:stop'), restart: () => invoke('server:restart'), status: () => invoke('server:status'), getPort: () => invoke<number>('server:get-port') },
  room: { create: (payload: unknown) => invoke('room:create', payload), join: (payload: unknown) => invoke('room:join', payload), status: (roomId: string) => invoke('room:status', roomId), destroy: (roomId: string) => invoke('room:destroy', roomId) },
  network: { getLocalIP: () => invoke<string>('network:get-local-ip'), getAllIPs: () => invoke<string[]>('network:get-all-ips'), checkInternet: () => invoke<boolean>('network:check-internet'), checkSameSubnet: (a: string, b: string) => invoke<boolean>('network:check-same-subnet', a, b), scanLanDevices: () => invoke('network:scan-lan-devices') },
  fs: { openFileDialog: () => invoke<string[]>('fs:open-file-dialog'), openFolderDialog: () => invoke<string>('fs:open-folder-dialog'), saveDialog: (defaultPath: string) => invoke<string>('fs:save-dialog', defaultPath), showInExplorer: (targetPath: string) => invoke('fs:show-in-explorer', targetPath), openPath: (targetPath: string) => invoke('fs:open-path', targetPath), getDownloadsPath: () => invoke<string>('fs:get-downloads-path'), getTempPath: () => invoke<string>('fs:get-temp-path'), getAppDataPath: () => invoke<string>('fs:get-app-data-path'), clearTempFiles: () => invoke<{ freedMB: number }>('fs:clear-temp-files'), getTempSize: () => invoke<number>('fs:get-temp-size'), getFileMetadata: (paths: string[]) => invoke('fs:get-file-metadata', paths), readFileChunk: (filePath: string, start: number, length: number) => invoke<string>('fs:read-file-chunk', filePath, start, length), sha256File: (filePath: string) => invoke<string>('fs:sha256-file', filePath) },
  win: { openHotspotSettings: () => invoke('win:open-hotspot-settings'), openNetworkSettings: () => invoke('win:open-network-settings'), openWifiSettings: () => invoke('win:open-wifi-settings'), setupFirewall: () => invoke<boolean>('win:setup-firewall'), checkFirewall: () => invoke<boolean>('win:check-firewall'), enableStartup: () => invoke('win:enable-startup'), disableStartup: () => invoke('win:disable-startup'), isStartupEnabled: () => invoke<boolean>('win:is-startup-enabled') },
  window: { minimize: () => invoke('window:minimize'), maximize: () => invoke('window:maximize'), close: () => invoke('window:close'), isMaximized: () => invoke<boolean>('window:is-maximized'), setTitle: (title: string) => invoke('window:set-title', title) },
  notify: { transferComplete: (title: string, body: string) => invoke('notify:transfer-complete', title, body), deviceConnected: (deviceName: string) => invoke('notify:device-connected', deviceName), transferRequest: (filename: string) => invoke('notify:transfer-request', filename) },
  webcam: { getDevices: () => invoke('webcam:get-devices'), requestPermission: () => invoke<boolean>('webcam:request-permission') }
});
