import { sha256File } from '@/services/fileChunker';
import { SignalingClient, type SignalingMessage } from './SignalingClient';
const ICE_CONFIG: RTCConfiguration = { iceServers: [{ urls: 'stun:stun.l.google.com:19302' }, { urls: 'stun:stun1.l.google.com:19302' }, { urls: 'stun:stun.cloudflare.com:3478' }, { urls: 'stun:stun.nextcloud.com:443' }, { urls: 'turn:openrelay.metered.ca:80', username: 'openrelayproject', credential: 'openrelayproject' }], iceCandidatePoolSize: 10 };
export class WebRTCService {
  private pc: RTCPeerConnection | null = null; private dataChannel: RTCDataChannel | null = null; private signaling: SignalingClient | null = null; private readonly chunkSize = 64 * 1024; private readonly bufferThreshold = 1024 * 1024;
  async connectAsHost(roomId: string, signalingURL: string): Promise<void> { this.pc = new RTCPeerConnection(ICE_CONFIG); this.dataChannel = this.pc.createDataChannel('filebeam', { ordered: true }); this.dataChannel.binaryType = 'arraybuffer'; this.signaling = new SignalingClient(signalingURL, roomId, (message) => void this.handleSignal(message)); await this.signaling.connect(); this.pc.onicecandidate = (event) => { if (event.candidate) this.signaling?.send({ type: 'ice_candidate', candidate: event.candidate.toJSON() }); }; const offer = await this.pc.createOffer(); await this.pc.setLocalDescription(offer); this.signaling.send({ type: 'offer', sdp: offer }); }
  async connectAsGuest(roomId: string, signalingURL: string): Promise<void> { this.pc = new RTCPeerConnection(ICE_CONFIG); this.pc.ondatachannel = (event) => { this.dataChannel = event.channel; this.dataChannel.binaryType = 'arraybuffer'; }; this.signaling = new SignalingClient(signalingURL, roomId, (message) => void this.handleSignal(message)); await this.signaling.connect(); this.pc.onicecandidate = (event) => { if (event.candidate) this.signaling?.send({ type: 'ice_candidate', candidate: event.candidate.toJSON() }); }; }
  private async handleSignal(message: SignalingMessage): Promise<void> { if (!this.pc) return; if (message.type === 'offer' && message.sdp) { await this.pc.setRemoteDescription(message.sdp); const answer = await this.pc.createAnswer(); await this.pc.setLocalDescription(answer); this.signaling?.send({ type: 'answer', sdp: answer }); } else if (message.type === 'answer' && message.sdp) { await this.pc.setRemoteDescription(message.sdp); this.signaling?.disconnectAfterDelay(); } else if (message.type === 'ice_candidate' && message.candidate) { await this.pc.addIceCandidate(message.candidate); } }
  async sendFile(file: File, onProgress: (payload: { bytesUploaded: number; totalBytes: number; speed: number }) => void): Promise<void> { if (!this.dataChannel) throw new Error('WebRTC data channel not ready'); this.dataChannel.send(JSON.stringify({ type: 'file_meta', filename: file.name, filesize: file.size, filetype: file.type, checksum: await sha256File(file) })); let offset = 0; let sent = 0; const startedAt = performance.now(); while (offset < file.size) { while ((this.dataChannel.bufferedAmount ?? 0) > this.bufferThreshold) await new Promise((resolve) => setTimeout(resolve, 8)); const chunk = await file.slice(offset, offset + this.chunkSize).arrayBuffer(); this.dataChannel.send(chunk); offset += chunk.byteLength; sent += chunk.byteLength; const elapsed = Math.max((performance.now() - startedAt) / 1000, 0.001); onProgress({ bytesUploaded: sent, totalBytes: file.size, speed: sent / elapsed }); } this.dataChannel.send(JSON.stringify({ type: 'file_end', filename: file.name })); }
  disconnect(): void { this.dataChannel?.close(); this.pc?.close(); }
}
